services:
  # 1. EL PROXY (NGINX) - La puerta de entrada
  nginx:
    image: nginx:alpine
    container_name: fitmanager-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  # 2. EL BACKEND (LARAVEL)
  backend:
    build:
      context: ./backend    # <--- FÍJATE: Apunta a la carpeta backend
      dockerfile: Dockerfile
    container_name: fitmanager-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    # Comando para arrancar Laravel en el puerto 8000
    command: php artisan serve --host=0.0.0.0 --port=8000

  # 3. EL FRONTEND (WEB)
  frontend:
    build:
      context: ./frontend   # <--- FÍJATE: Apunta a la carpeta frontend
      dockerfile: Dockerfile
    container_name: fitmanager-frontend
    volumes:
        - ./frontend:/usr/share/nginx/html 
    # ------------------
    networks:
        - app-network

  # 4. BASE DE DATOS
  db:
    image: mysql:8.0
    container_name: fitmanager-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge